### ISSUE TITLE
Adding tidyverse to packages to load

### ISSUE THREAD

**Issue by francojc** [jerid-francom/project_francom#3]
I would add the tidyverse package all of your analysis `.Rmd` files.

```
library(tidyverse)
```

https://github.com/jerid-francom/project_francom/blob/919a95228cdeae85f0deb00a57cc443087c16301/analysis/1_acquire_data.Rmd

@jerid-francom

**Comment by jerid-francom** [comment]
I've added tidyverse to the analysis files. I used the `pacman::p_load()` function instead, however.
